version: '3.7'

services:

  nginx:
    build: ./requirements/nginx/
    image: inception_nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html
    env_file: 
      - .env
    ports: 
      - 443:443
    networks:
      - internal_network
    restart: on-failure
  
  mariadb:
    build: ./requirements/mariadb/
    image: inception_mariadb
    container_name: mariadb
    volumes:
      - db_volume:/var/lib/mysql
    env_file: 
      - .env
    networks:
      - internal_network
    restart: on-failure
  
  wordpress:
    build: ./requirements/wordpress/
    image: inception_wordperss
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html
    env_file: 
      - .env
    networks:
      - internal_network
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: inception_adminer
    container_name: adminer
    networks:
      - internal_network
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - 500:8080
    depends_on:
      - mariadb
    restart: on-failure

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor:42
    ports:
      - 8080:8080
    networks:
      - internal_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  webPage:
    build: ./requirements/bonus/webPage
    image: web
    container_name: web
    restart: always
    ports:
      - 8085:80
    networks:
      - internal_network

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/marouane/data/mariadb
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/marouane/data/wordpress

networks:
  internal_network:
    name: 'internal_network'
    driver: bridge


